version: "3.4"
services:
  django:
    build: ./backend/webscraper
    ports:
      - "8000:8000"
    networks:
      webcrawler_network:
        # This is static so it can be reached if the dev server is running
        ipv4_address: 173.16.38.5

  angular:
    build: ./frontend/app
    ports:
      - "4200:4200"
    networks:
      webcrawler_network:
        # This is static so it can be reached if the dev server is running
        ipv4_address: 173.16.38.7
    links:
      - django # link this service to the api service

  pbs-base-image:
    image: pbs-base-image
    build:
      context: pbs

  pbs-head-node:
    image: pbs-head-node
    depends_on:
      - pbs-base-image
    tty: true
    build:
      context: pbs/pbs-head-node
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    privileged: true
    security_opt:
      - apparmor:unconfined
    hostname: pbs-head-node
    networks:
      webcrawler_network:
        aliases:
          - pbs-head-node
        # This is static so it can be reached if the dev server is running
        ipv4_address: 173.16.38.8

  pbs-sim-node:
    image: pbs-sim-node
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    depends_on:
      - pbs-head-node
    tty: true
    build:
      context: pbs/pbs-sim-node
    shm_size: '2gb'
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    privileged: true
    security_opt:
      - apparmor:unconfined
    hostname: pbs-sim-node
    networks:
      webcrawler_network:
        aliases:
          - pbs-sim-node
          # This is static so it can be reached if the dev server is running
        ipv4_address: 173.16.38.9

  db:
    image: postgres:12.1
    environment:
      - POSTGRES_DB=webcrawler-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

networks:
  webcrawler_network:
    ipam:
      config:
        - subnet: 173.16.38.0/18
