# Generated by Django 3.2.10 on 2023-01-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spider",
            name="completed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
