# Generated by Django 3.2.10 on 2023-01-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_spider_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="spider",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("exit", "Exit"),
                ],
                default="new",
                max_length=10,
            ),
        ),
    ]
