# Generated by Django 3.2.10 on 2023-01-07 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_auto_20230107_0053"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Inspetor",
            new_name="Inspector",
        ),
    ]
