# Generated by Django 4.1 on 2023-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_rename_spider_crawler_rename_spider_runner_crawler"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crawler",
            old_name="url",
            new_name="seed_url",
        ),
        migrations.AddField(
            model_name="crawler",
            name="max_depth",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="crawler",
            name="max_pages",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="crawler",
            name="retry",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="crawler",
            name="robot_file_url",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="crawler",
            name="sleep",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="crawler",
            name="threads",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="crawler",
            name="timeout",
            field=models.FloatField(default=10),
        ),
    ]
