# Generated by Django 4.1 on 2023-05-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_rename_url_crawler_seed_url_crawler_max_depth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectorValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.inspector"
                    ),
                ),
            ],
        ),
    ]
