# Generated by Django 4.1 on 2023-05-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_inspectorvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectorvalue",
            name="runner",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="base.runner"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inspectorvalue",
            unique_together={("value", "inspector")},
        ),
    ]
