# Generated by Django 4.1 on 2023-05-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_inspectorvalue_runner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="runner",
            options={},
        ),
        migrations.AlterField(
            model_name="runner",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Running", "Running"),
                    ("Completed", "Completed"),
                    ("Exit", "Exit"),
                    ("Paused", "Paused"),
                ],
                default="New",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inspectorvalue",
            unique_together={("value", "inspector", "runner")},
        ),
    ]
