# Generated by Django 4.1 on 2023-05-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_alter_runner_options_alter_runner_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawler",
            name="excluded_urls",
            field=models.TextField(blank=True),
        ),
    ]
