# Generated by Django 4.1 on 2023-05-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_crawler_excluded_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspector",
            name="attribute",
            field=models.CharField(
                choices=[
                    ("href", "Href"),
                    ("name", "Name"),
                    ("src", "Src"),
                    ("title", "Title"),
                    ("value", "Value"),
                ],
                default="value",
                max_length=25,
            ),
        ),
    ]
