# Generated by Django 4.1 on 2023-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_inspectorvalue_attribute_alter_inspectorvalue_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspector",
            name="attribute",
            field=models.CharField(
                choices=[
                    ("href", "Href"),
                    ("name", "Name"),
                    ("src", "Src"),
                    ("title", "Title"),
                    ("value", "Value"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
