# Generated by Django 4.1 on 2023-05-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_alter_inspector_attribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectorvalue",
            name="attribute",
            field=models.TextField(blank=True, null=True),
        ),
    ]
