# Generated by Django 4.1 on 2023-05-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_alter_inspectorvalue_attribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspector",
            name="selector",
            field=models.TextField(),
        ),
    ]
