# Generated by Django 4.1 on 2023-05-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_product_remove_crawler_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawler",
            name="scope_divs",
            field=models.TextField(blank=True),
        ),
    ]
