# Generated by Django 4.1 on 2023-05-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0025_crawler_scope_divs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawler",
            name="robot_file_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
