# Generated by Django 4.1 on 2023-05-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0026_alter_crawler_robot_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="runner",
            name="name",
            field=models.CharField(default="New runner", max_length=50),
        ),
    ]
