# Generated by Django 4.1 on 2023-05-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0027_runner_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawler",
            name="max_collected_docs",
            field=models.PositiveIntegerField(default=20),
        ),
    ]
