# Generated by Django 4.1 on 2023-05-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0029_action_clickaction_scrollaction_waitaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionchain",
            name="name",
            field=models.CharField(default="default-actions", max_length=100),
        ),
    ]
