# Generated by Django 4.1 on 2023-05-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0030_actionchain_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionchain",
            name="event",
            field=models.CharField(
                choices=[("before", "Before"), ("after", "After")],
                default="before",
                max_length=10,
            ),
        ),
    ]
