# Generated by Django 4.1 on 2023-05-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0031_actionchain_event"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.AddField(
            model_name="action",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="inspector",
            name="attribute",
            field=models.CharField(
                blank=True,
                choices=[
                    ("href", "Href"),
                    ("name", "Name"),
                    ("src", "Src"),
                    ("title", "Title"),
                    ("value", "Value"),
                ],
                default="",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="inspectorvalue",
            name="attribute",
            field=models.TextField(blank=True, default=""),
        ),
    ]
