# Generated by Django 4.1 on 2023-05-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0032_delete_product_action_deleted_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterUniqueTogether(
            name="action",
            unique_together=set(),
        ),
    ]
