# Generated by Django 4.1 on 2023-06-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0034_alter_inspectorvalue_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inspectorvalue",
            unique_together={("value", "inspector", "url")},
        ),
    ]
