# Generated by Django 4.1 on 2023-06-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0036_alter_inspectorvalue_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawler",
            name="parsing_algorithm",
            field=models.CharField(
                choices=[
                    ("BFS_TOP_DOWN", "Bfs Top Down"),
                    ("BFS_BOTTOM_UP", "Bfs Bottom Up"),
                ],
                default="BFS_BOTTOM_UP",
                max_length=20,
            ),
        ),
    ]
