# Generated by Django 4.1 on 2023-06-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0037_crawler_parsing_algorithm"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawler",
            name="allow_multi_elements",
            field=models.BooleanField(default=False),
        ),
    ]
