# Generated by Django 4.1 on 2023-06-17 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0039_document_inspectorvalue_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="base.template",
            ),
        ),
    ]
