# Generated by Django 4.1 on 2023-06-17 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0040_alter_document_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectorvalue",
            name="document",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="base.document",
            ),
        ),
    ]
