# Generated by Django 4.1 on 2023-06-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0041_inspectorvalue_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexer",
            name="b_parameter",
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name="indexer",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="indexer",
            name="k_parameter",
            field=models.FloatField(default=1.75),
        ),
    ]
