# Generated by Django 4.1 on 2023-06-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0042_indexer_b_parameter_indexer_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexer",
            name="skip_words",
            field=models.TextField(blank=True),
        ),
    ]
