# Generated by Django 4.1 on 2023-06-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0043_indexer_skip_words"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexer",
            name="small_words_threshold",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
