# Generated by Django 4.1 on 2023-06-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0044_indexer_small_words_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexer",
            name="dictionary",
            field=models.CharField(default="wikidata-entities.tsv", max_length=200),
        ),
    ]
