# Generated by Django 4.1 on 2023-06-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0045_indexer_dictionary"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexer",
            name="q_gram_q",
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="indexer",
            name="q_gram_use_synonym",
            field=models.BooleanField(default=True),
        ),
    ]
