# Generated by Django 4.1 on 2023-06-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0046_indexer_q_gram_q_indexer_q_gram_use_synonym"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspector",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("image", "Image"), ("text", "Text"), ("link", "Link")],
                default="text",
                max_length=10,
            ),
        ),
    ]
