# Generated by Django 4.1 on 2023-07-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0047_inspector_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexer",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Dictionary", "Dictionary"),
                    ("Indexing", "Indexing"),
                    ("Completed", "Completed"),
                    ("Exit", "Exit"),
                ],
                default="New",
                max_length=10,
            ),
        ),
    ]
