# Generated by Django 4.1 on 2023-07-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0048_alter_indexer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawler",
            name="show_browser",
            field=models.BooleanField(default=False),
        ),
    ]
