# Generated by Django 4.1 on 2023-07-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0050_actionchain_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="runner",
            name="machine",
            field=models.CharField(default="localhost", max_length=225),
        ),
    ]
