# Generated by Django 4.1 on 2023-07-09 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0053_inspectorvalue_link_fragment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectorvalue",
            name="link_fragment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="base.linkfragment"
            ),
        ),
    ]
