# Generated by Django 4.1 on 2023-07-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0054_alter_inspectorvalue_link_fragment"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexer",
            name="weight_words",
            field=models.TextField(blank=True),
        ),
    ]
