# Generated by Django 4.1 on 2023-07-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0055_indexer_weight_words"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexer",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
