# Generated by Django 4.1 on 2023-07-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0056_alter_indexer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspector",
            name="variable_name",
            field=models.CharField(default="", max_length=10),
        ),
    ]
