# Generated by Django 4.1 on 2023-07-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0057_inspector_variable_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspector",
            name="variable_name",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
