# Generated by Django 4.1 on 2023-07-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0058_alter_inspector_variable_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexer",
            name="boosting_formula",
            field=models.TextField(blank=True),
        ),
    ]
