# Generated by Django 4.1 on 2023-07-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0059_indexer_boosting_formula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspector",
            name="variable_name",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
