# Generated by Django 4.1 on 2023-07-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0060_alter_inspector_variable_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspector",
            name="variable_name",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
