# Generated by Django 4.1 on 2023-07-17 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0062_inspector_clean_up_expression"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visited_pages", models.PositiveIntegerField(default=0)),
                ("avg_loading_time", models.FloatField(default=0)),
                ("avg_page_size", models.FloatField(default=0)),
                ("http_codes", models.JSONField(default="")),
                (
                    "runner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="base.runner"
                    ),
                ),
            ],
        ),
    ]
