# Generated by Django 4.1 on 2023-07-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0063_statistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistics",
            name="average_docs_per_page",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="statistics",
            name="average_processing_time",
            field=models.FloatField(default=0),
        ),
    ]
