# Generated by Django 4.1 on 2023-07-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0064_statistics_average_docs_per_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="hash_code",
            field=models.CharField(default="", max_length=40),
        ),
    ]
