# Generated by Django 4.1 on 2023-09-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0065_document_hash_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkfragment",
            name="fragment",
            field=models.CharField(max_length=250),
        ),
    ]
