# Generated by Django 4.1 on 2023-09-15 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0066_alter_linkfragment_fragment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectorvalue",
            name="document",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.document",
            ),
        ),
    ]
