# Generated by Django 4.1 on 2023-09-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0067_alter_inspectorvalue_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawler",
            name="parsing_algorithm",
            field=models.CharField(
                choices=[("BFS", "Bfs"), ("DFS", "Dfs")], default="DFS", max_length=20
            ),
        ),
    ]
