# Generated by Django 4.1 on 2023-12-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0068_alter_crawler_parsing_algorithm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistics",
            name="http_codes",
            field=models.JSONField(default=dict),
        ),
    ]
